-- 0020_ai_endpoints_ide.sql
-- RECONCILED NO-OP (fire-61, 2026-10-01). Original content retired.
--
-- The original migration ALTERed the `ai_endpoints` table (11 ADD COLUMNs + 1 index)
-- for the in-admin AI-endpoint IDE. That feature was REMOVED platform-wide: the
-- UI-authored AI-endpoint system (ai_endpoints D1 table + /api/ai/:slug/:endpoint
-- dispatcher) was replaced by code-defined Functions on Workers for Platforms
-- (docs/decisions/0035-custom-code-endpoints-wfp.md, docs/FUNCTIONS-CONVERGENCE.md;
-- root CLAUDE.md "Removed - never reintroduce").
--
-- Production has NO `ai_endpoints` table, so the original ALTER TABLE statements can
-- never succeed there - this file is exactly why a blanket
-- `wrangler d1 migrations apply` died (fire-60). Rewritten as a safe no-op so the
-- migration can be tracked as applied against prod reality. NEVER recreate
-- ai_endpoints. Full audit: docs/migrations-reconcile-2026-10.md.
SELECT 1;
