-- Migration: 0516_drop_phone_otps
-- RECONCILED NO-OP (fire-61, 2026-10-01). Original content retired.
--
-- The original migration dropped the orphaned `phone_otps` table + its index
-- (phone OTP auth removed in commit b555680). It was NEVER applied to production:
-- `phone_otps` still exists there, and current doctrine (root CLAUDE.md § Removed)
-- treats the residual `users.phone` column and `phone_otps` table as INERT orphans
-- that are safe to keep - no code reads or writes them.
--
-- The fire-61 reconciliation ran under a strict NEVER-DROP constraint, so instead
-- of executing a destructive statement years after it was authored, this file is
-- now a no-op. If the drop is ever actually wanted, author it as a NEW deliberate
-- migration (D1 Time Travel gives 30 days of recovery). Full audit:
-- docs/migrations-reconcile-2026-10.md.
SELECT 1;
