/**
 * @module services/content_version
 * @description Pure content versioning utilities for tracking draft iterations.
 *
 * Provides immutable version snapshots, line-level diffs between two content
 * strings, and safe rollback selection from a version list. Zero I/O — the
 * caller owns persistence.
 *
 * ## Version shape
 *
 * | Field    | Description                       |
 * | -------- | --------------------------------- |
 * | `id`     | UUIDv4 generated by the factory   |
 * | `siteId` | Owning site identifier            |
 * | `version`| Human label (e.g. `"v1.2.3"`)     |
 * | `content`| The full content snapshot         |
 * | `reason` | Optional reason for this version  |
 * | `createdAt` | ISO 8601 UTC timestamp        |
 *
 * @example
 * ```ts
 * const v1 = createVersion('site_abc', '# Hello', 'v1');
 * const v2 = createVersion('site_abc', '# Hello\n\nNew paragraph', 'v2', 'Add intro');
 * const diff = diffVersions(v1.content, v2.content);
 * // { added: ['', 'New paragraph'], removed: [], changed: [] }
 * const rollback = rollbackVersion([v1, v2], 'v1');
 * // { ...v1 }
 * ```
 */

// ---------------------------------------------------------------------------
// ContentVersion — the canonical version record shape
// ---------------------------------------------------------------------------

/** A single content version snapshot. */
export interface ContentVersion {
  /** ISO 8601 UTC timestamp when the snapshot was created. */
  readonly createdAt: string;
  /** The full content body at this version. */
  readonly content: string;
  /** UUIDv4 — generated by {@link createVersion}. */
  readonly id: string;
  /** Optional human-readable reason for creating this version. */
  readonly reason?: string;
  /** The site this version belongs to. */
  readonly siteId: string;
  /** Human version label (e.g. `"v1"`, `"draft-3"`, `"2026-06-29"`). */
  readonly version: string;
}

/** The result of comparing two content versions. */
export interface ContentDiff {
  /** Lines present in `newer` but absent from `older`. */
  readonly added: string[];
  /** Lines that differ between the two (matching line number, different text). */
  readonly changed: string[];
  /** Lines present in `older` but absent from `newer`. */
  readonly removed: string[];
}

// ---------------------------------------------------------------------------
// createVersion — factory
// ---------------------------------------------------------------------------

/**
 * Build a fully-typed ContentVersion record.
 *
 * @param siteId  - The owning site identifier.
 * @param content - The full content snapshot to version.
 * @param version - Human-readable version label.
 * @param reason  - Optional reason for this version (e.g. "After AI polish").
 * @returns A complete ContentVersion with generated id and timestamp.
 *
 * @example
 * const v = createVersion('site_1', '# Hello', 'v1', 'Initial draft');
 * // { id: '…', siteId: 'site_1', content: '# Hello', version: 'v1', reason: 'Initial draft', createdAt: '…' }
 */
export function createVersion(
  siteId: string,
  content: string,
  version: string,
  reason?: string,
): ContentVersion {
  return {
    content,
    createdAt: new Date().toISOString(),
    id: crypto.randomUUID(),
    reason,
    siteId,
    version,
  };
}

// ---------------------------------------------------------------------------
// diffVersions — line-level comparison
// ---------------------------------------------------------------------------

/**
 * Compare two content strings line-by-line and report what was added, removed,
 * or changed.
 *
 * A line is considered **changed** when the same line index exists in both
 * snapshots but the text differs. **Added** lines exist in the newer string
 * but not the older; **removed** lines exist in the older but not the newer.
 *
 * Line count is determined by `split('\n')` — the trailing newline produces
 * an empty trailing token. Callers that trim trailing newlines will see
 * the expected result (the diff skips matching empty trailing lines).
 *
 * @param older - The earlier content string.
 * @param newer - The later content string.
 * @returns A structured ContentDiff with added, removed, and changed arrays.
 *
 * @example
 * diffVersions('a\nb\nc', 'a\nx\nc');
 * // { added: [], removed: [], changed: ['x'] }  (line 1 changed from "b" to "x")
 *
 * @example
 * diffVersions('a\nb', 'a\nb\nc\nd');
 * // { added: ['c', 'd'], removed: [], changed: [] }
 *
 * @example
 * diffVersions('a\nb\nc', 'a');
 * // { added: [], removed: ['b', 'c'], changed: [] }
 */
export function diffVersions(older: string, newer: string): ContentDiff {
  const oldLines = older.split('\n');
  const newLines = newer.split('\n');
  const maxLen = Math.max(oldLines.length, newLines.length);

  const added: string[] = [];
  const removed: string[] = [];
  const changed: string[] = [];

  for (let i = 0; i < maxLen; i++) {
    const oldLine = i < oldLines.length ? oldLines[i] : undefined;
    const newLine = i < newLines.length ? newLines[i] : undefined;

    if (oldLine === undefined && newLine !== undefined) {
      // Line exists only in new
      added.push(newLine);
    } else if (newLine === undefined && oldLine !== undefined) {
      // Line exists only in old
      removed.push(oldLine);
    } else if (oldLine !== undefined && newLine !== undefined && oldLine !== newLine) {
      // Both exist but differ (the two branches above already handled the
      // add/remove cases, so here both lines are defined — no non-null needed)
      changed.push(newLine);
    }
  }

  return { added, changed, removed };
}

// ---------------------------------------------------------------------------
// rollbackVersion — select a target version from a list
// ---------------------------------------------------------------------------

/**
 * Locate a version by its `version` label and return a clean reference.
 *
 * Returns the matching `ContentVersion` (shallow clone) when found, or
 * `null` when no version matches `targetVersion`. The source array is
 * never mutated.
 *
 * @param versions       - All versions to search.
 * @param targetVersion  - The version label to find (e.g. `"v1"`).
 * @returns The matching ContentVersion, or `null` if not found.
 *
 * @example
 * const v1 = createVersion('s1', '# A', 'v1');
 * const v2 = createVersion('s1', '# B', 'v2');
 * const target = rollbackVersion([v1, v2], 'v1');
 * // { ...v1 }
 *
 * @example
 * rollbackVersion([v1, v2], 'nonexistent');
 * // null
 */
export function rollbackVersion(
  versions: readonly ContentVersion[],
  targetVersion: string,
): ContentVersion | null {
  const found = versions.find((v) => v.version === targetVersion);
  return found ? { ...found } : null;
}
