// AUTO-GENERATED by scripts/gen-app-screenshots.mjs — do not edit by hand.
// Per-service "telling images" (homepage og:image) for the app detail carousel. The detail
// component appends each repo's GitHub social card, so every service still gets a card even
// when its homepage exposes no og:image. Re-run the script to refresh.
export const APP_SCREENSHOTS: Readonly<Record<string, readonly string[]>> = {
  "umami": [
    "https://umami.is/opengraph-image-j8qpfc.png?opengraph-image.061x5-78_1ett.png"
  ],
  "listmonk": [
    "https://listmonk.app/static/images/thumbnail.webp"
  ],
  "open-webui": [
    "https://openwebui.com/og-image.png"
  ],
  "lobe-chat": [
    "https://lobehub.com/assets/cao-og.webp"
  ],
  "langflow": [
    "https://www.langflow.org/images/og-image.png"
  ],
  "litellm": [
    "https://cdn.prod.website-files.com/69eb241da3f923869c226875/6a63c4a8dab885977d66cde8_LiteLLM%20OG.png"
  ],
  "phoenix": [
    "https://arize.com/wp-content/uploads/2026/05/Phoenix.jpg"
  ],
  "payload": [
    "https://payloadcms.com/images/og-image.jpg"
  ]
} as const;
