/**
 * Worker environment bindings type definitions
 * This file is auto-generated by wrangler types but we define it manually for development
 */

interface Env {
  // ==========================================================================
  // KV Namespaces
  // ==========================================================================
  CACHE_KV: KVNamespace;

  // ==========================================================================
  // R2 Buckets
  // ==========================================================================
  SITES_BUCKET: R2Bucket;

  // ==========================================================================
  // Queues
  // ==========================================================================
  WORKFLOW_QUEUE: Queue;

  // ==========================================================================
  // Workflows
  // ==========================================================================
  SITE_GENERATION_WORKFLOW: Workflow;

  // ==========================================================================
  // Durable Objects
  // ==========================================================================
  RATE_LIMITER: DurableObjectNamespace;

  // ==========================================================================
  // Environment (from vars)
  // ==========================================================================
  ENVIRONMENT: 'development' | 'test' | 'staging' | 'production';
  LOG_LEVEL: 'debug' | 'info' | 'warn' | 'error';

  // ==========================================================================
  // Supabase (from secrets)
  // ==========================================================================
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;

  // ==========================================================================
  // Stripe (from secrets)
  // ==========================================================================
  STRIPE_SECRET_KEY: string;
  STRIPE_PUBLISHABLE_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;

  // ==========================================================================
  // Cloudflare (from secrets)
  // ==========================================================================
  CF_API_TOKEN: string;
  CF_ZONE_ID: string;
  CF_ACCOUNT_ID: string;

  // ==========================================================================
  // AI Providers (from secrets)
  // ==========================================================================
  OPENAI_API_KEY?: string;
  OPEN_ROUTER_API_KEY?: string;
  GROQ_API_KEY?: string;

  // ==========================================================================
  // Google (from secrets)
  // ==========================================================================
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  GOOGLE_PLACES_API_KEY: string;

  // ==========================================================================
  // External Services (from secrets)
  // ==========================================================================
  SENDGRID_API_KEY: string;
  CHATWOOT_API_URL?: string;
  CHATWOOT_API_KEY?: string;
  NOVU_API_KEY?: string;

  // ==========================================================================
  // Observability (from secrets)
  // ==========================================================================
  SENTRY_DSN: string;

  // ==========================================================================
  // Sale Webhook (from secrets)
  // ==========================================================================
  SALE_WEBHOOK_URL?: string;
  SALE_WEBHOOK_SECRET?: string;

  // ==========================================================================
  // Feature Flags (from vars)
  // ==========================================================================
  METERING_PROVIDER?: 'lago' | 'internal';
  ENABLE_POSTCARDS?: string;
}

// Workflow type (basic definition)
interface Workflow {
  create(options: { id: string; params: unknown }): Promise<WorkflowInstance>;
  get(id: string): Promise<WorkflowInstance | null>;
}

interface WorkflowInstance {
  id: string;
  status: () => Promise<WorkflowStatus>;
  pause: () => Promise<void>;
  resume: () => Promise<void>;
  terminate: () => Promise<void>;
  restart: () => Promise<void>;
}

interface WorkflowStatus {
  status: 'running' | 'paused' | 'complete' | 'errored' | 'terminated';
  output?: unknown;
  error?: string;
}
